import { PetData } from 'System/data/pet/PetData'
import { ThingData } from 'System/data/thing/ThingData'

/**
 * <在此键入枚举的中文名称>枚举类。
 * Code generated by Bat&Perl.
 *
 * @author Administrator
 *
 */
export class EnumRankRule {
    /**<角色装备>。*/
    static LIST_ROLE = 1;
    /**<祝福装备>。*/
    static LIST_ZHU_FU = 2;
    /**<武颜装备>。*/
    static LIST_HONG_YAN = 3;

    /**<祝福系统装备数量>。*/
    static ZHUFU_PANEL_EQUIP_NUM = 4;

    /**获取装备格子数量*/
    static getEquipNumByListType(type: number): number {
        let tmpNum: number = 0;
        switch (type) {
            case EnumRankRule.LIST_ROLE:
                tmpNum = ThingData.All_EQUIP_NUM+1;
                break;
            case EnumRankRule.LIST_ZHU_FU:
                tmpNum = EnumRankRule.ZHUFU_PANEL_EQUIP_NUM;
                break;
            case EnumRankRule.LIST_HONG_YAN:
                tmpNum = PetData.EQUIP_NUM_PER_PET;
                break;
            default:
        }
        return tmpNum;
    }
}
