/**
	 * <在这里键入Item的中文名>Item的Vo。
	 * 
	 * 本文件代码由模板生成，你可能需要继续修改其他代码文件才能正常使用。
	 * Code generated by Bat&Perl.
	 * 
	 * @author Administrator
	 * 
	 */
export class JjrRewardsItemData {
    /**
     * 1.不可领取 2.可领取 3.已领取	见宏GOD_LOAD_AWARD_DONE_GET
     */
    m_ucStatus: number = 0;
    cfg: GameConfig.StageDayCfgM;

}
