import { HfhdTabItemData } from 'System/data/HfhdTabItemData'

/**
 * <在这里键入Item的中文名>Item的Vo。
 * 
 * 本文件代码由模板生成，你可能需要继续修改其他代码文件才能正常使用。
 * Code generated by Bat&Perl.
 * 
 * @author Administrator
 * 
 */
export class JjrTabItemData {
    /**进阶日类型*/
    m_ucType: number = 0;
    mcRewardStatus: number = 0;
}
