import { PropUtil } from 'System/utils/PropUtil'
/**
 * <在这里键入Item的中文名>Item的Vo。
 *
 * 本文件代码由模板生成，你可能需要继续修改其他代码文件才能正常使用。
 * Code generated by Bat&Perl.
 *
 * @author Administrator
 *
 */
export class MagiccubeAttItemData {
    addVal: number = 0;
    nextVal: number = 0;
    propStr: string;
    private _propId: number = 0;

    get propId(): number {
        return this._propId;
    }

    set propId(value: number) {
        this._propId = value;
        this.propStr = PropUtil.getPropStrByPropId(this._propId);
    }
}
