/**
	 * <在这里键入Item的中文名>Item的Vo。
	 * 
	 * 本文件代码由模板生成，你可能需要继续修改其他代码文件才能正常使用。
	 * Code generated by Bat&Perl.
	 * 
	 * @author teppei
	 * 
	 */
export class ShouHuNvShenItemData {
    diffConfig: GameConfig.PinstanceDiffBonusM;

    /**是否终生首通。*/
    isLifePassed: boolean = false;

    /**是否今日首通。*/
    isTodayPassed: boolean = false;

    /**是否已领取首通奖励。*/
    isGiftDrawn: boolean = false;


}
