import { RewardIconItemData } from 'System/data/vo/RewardIconItemData'

/**
	 * <在这里键入Item的中文名>Item的Vo。
	 *
	 * 本文件代码由模板生成，你可能需要继续修改其他代码文件才能正常使用。
	 * Code generated by Bat&Perl.
	 *
	 * @author Administrator
	 *
	 */
export class TgbjRecordItemData {
    roleId: Protocol.RoleID;
    roleName: string;
    iconItemData: RewardIconItemData;
    /**抽奖类型*/
    type: number = 0;
    /**记录类型*/
    recordType: number = 0;
    thingConfig: GameConfig.ThingConfigM;
}
