  /**
	 * <在这里键入Item的中文名>Item的Vo。
	 *
	 * 本文件代码由模板生成，你可能需要继续修改其他代码文件才能正常使用。
	 * Code generated by Bat&Perl.
	 *
	 * @author Administrator
	 *
	 */
export class EquipEnhanceAttItemData {
    public propId: number = 0;
    public propStr: string;
    public baseVal: number = 0;
    public beforeVal: number = 0;
    public afterVal: number = 0;
}
