import { Macros } from 'System/protocol/Macros'

/**
 * <在此键入枚举的中文名称>枚举类。
 * Code generated by Bat&Perl.
 *
 * @author Administrator
 *
 */
export class EnumTzjhRule {
    /**<投资计划配置表流水号ID>。*/
    static TZJH_ID = 1;
    /**<投资计划最大天数>。*/
    static TZJH_MAX_DAY = 7;

    /**<每天奖励>。*/
    static TYPE_DAY: number = Macros.JUHS_GET_TYPE_NORMAL;
    /**<在线奖励>。*/
    static TYPE_ONLINE: number = Macros.JUHS_GET_TYPE_ONLINE;
    /**<VIP专属奖励>。*/
    static TYPE_VIP: number = Macros.JUHS_GET_TYPE_VIP;

    /**<VIP专属奖励等级>。*/
    static VIP_REWARD_LEVEL = 6;

    //聚划算(投资计划)在线时长 第一个掉落礼包ID，后面的要按顺序配7个啊
    static JUHS_ONLINE_BASE_GIFT_ID = 60010088;
    //聚划算(投资计划)VIP等级 第一个掉落礼包ID，后面的要按顺序配7个啊
    static JUHS_VIP_BASE_GIFT_ID = 60010095;


}
