/**
* <所有仙盟列表数据>Item的Vo。
* 
* 本文件代码由模板生成，你可能需要继续修改其他代码文件才能正常使用。
* Code generated by Bat&Perl.
* 
* @author hearyw
* 
*/
export class GuildListInfoItemData {

    /**仙盟排名*/
    guildRank: number = 0;

    /**仙盟名称*/
    guildName: string;

    /**仙盟盟主*/
    guildLeader: string;

    /**仙盟等级*/
    guildLevel: number = 0;

    /**仙盟人数*/
    guildMemberNum: number = 0;

    /**仙盟总战斗力*/
    guildTotal: number = 0;

    /**仙盟盟主vip等级*/
    vipLevel: number = 0;

    /**仙盟最多人数*/
    maxNum: number = 0;

    /**仙盟ID*/
    guildID: number = 0;

    /**自己宗门*/
    isMyGuild: boolean;

    leaderRoleID: Protocol.RoleID;
}
