/**
* 剑帝遗迹Item的Vo。
* 
* 本文件代码由模板生成，你可能需要继续修改其他代码文件才能正常使用。
* Code generated by Bat&Perl.
* 
* @author teppei
* 
*/
export class JdyjItemData {
    /**副本id，剧情副本分2种*/
    pinID: number = 0;
    pinstanceConfig: GameConfig.PinstanceConfigM;

    diffConfig: GameConfig.PinstanceDiffBonusM;
    /**头像名字编号*/
    imgId: number = 0;

    /**是否等级受限。*/
    limitedLv = 0;

    /**是否终生首通。*/
    isLifePassed = false;

    /**是否今日首通。*/
    isTodayPassed = false;
    
    isValid = false;

    /**是否是关联特殊vip的副本*/
    isLinkVip: boolean = false;
    /**是否关联特殊vip是否已经购买*/
    isLinkVipHasBuy: boolean = false;
}
