import { PropUtil } from 'System/utils/PropUtil';
/**
 * <在这里键入Item的中文名>Item的Vo。
 *
 * 本文件代码由模板生成，你可能需要继续修改其他代码文件才能正常使用。
 * Code generated by Bat&Perl.
 *
 * @author Administrator
 *
 */
export class HeroAttItemData {
    private _macroId: number = 0;
    addVal: number = 0;
    nextVal: number = 0;
    configIndex: number = 0;
    private _propId: number = 0;

    /**宏ID*/
    get macroId(): number {
        return this._macroId;
    }
     
    set macroId(value: number) {
        this._macroId = value;
        this._propId = PropUtil.getPropIdByPropMacros(this._macroId);
    }

    get propId(): number {
        return this._propId;
    }
}
