using System;
namespace Uts {
	public class Registers {
		public static void Register(IntPtr env) {
			Native.jvm_reg_start(env);
			Native.jvm_reg_mod_start(env, "UnityEngine");
			ObjectWrap.Register(env);
			TypeWrap.Register(env);
			ComponentWrap.Register(env);
			BehaviourWrap.Register(env);
			MonoBehaviourWrap.Register(env);
			ColliderWrap.Register(env);
			TextureWrap.Register(env);
			RendererWrap.Register(env);
			PlayerPrefsWrap.Register(env);
			SpriteWrap.Register(env);
			AnimationCurveWrap.Register(env);
			AsyncOperationWrap.Register(env);
			NavMeshWrap.Register(env);
			NavMeshHitWrap.Register(env);
			NavMeshPathWrap.Register(env);
			BoxColliderWrap.Register(env);
			TextAssetWrap.Register(env);
			ShaderWrap.Register(env);
			MaterialWrap.Register(env);
			Texture2DWrap.Register(env);
			RenderTextureWrap.Register(env);
			MeshRendererWrap.Register(env);
			SkinnedMeshRendererWrap.Register(env);
			ParticleSystemRendererWrap.Register(env);
			GameObjectWrap.Register(env);
			TransformWrap.Register(env);
			AnimatorWrap.Register(env);
			CameraWrap.Register(env);
			RectTransformWrap.Register(env);
			ParticleSystemWrap.Register(env);
			AudioSourceWrap.Register(env);
			AudioClipWrap.Register(env);
			PointerEventDataWrap.Register(env);
			CanvasWrap.Register(env);
			CanvasGroupWrap.Register(env);
			UIBehaviourWrap.Register(env);
			ApplicationWrap.Register(env);
			ResolutionWrap.Register(env);
			ScreenWrap.Register(env);
			TimeWrap.Register(env);
			RectTransformUtilityWrap.Register(env);
			SystemInfoWrap.Register(env);
			GraphicsWrap.Register(env);
			LightWrap.Register(env);
			QualitySettingsWrap.Register(env);
			SceneManagerWrap.Register(env);
			ColorWrap.Register(env);
			Color32Wrap.Register(env);
			Vector4Wrap.Register(env);
			BoundsWrap.Register(env);
			QuaternionWrap.Register(env);
			RectWrap.Register(env);
			RectOffsetWrap.Register(env);
			KeyframeWrap.Register(env);
			AndroidJavaObjectWrap.Register(env);
			AndroidJavaClassWrap.Register(env);
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.UI");
			GraphicWrap.Register(env);
			MaskableGraphicWrap.Register(env);
			SelectableWrap.Register(env);
			TextWrap.Register(env);
			UITextWrap.Register(env);
			UITextUrlWrap.Register(env);
			ImageWrap.Register(env);
			RawImageWrap.Register(env);
			ActiveToggleWrap.Register(env);
			ActiveToggleGroupWrap.Register(env);
			SliderWrap.Register(env);
			ScrollRectWrap.Register(env);
			ScrollbarWrap.Register(env);
			DropdownWrap.Register(env);
			InputFieldWrap.Register(env);
			LayoutElementWrap.Register(env);
			LayoutRebuilderWrap.Register(env);
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "Tween");
			UITweenerWrap.Register(env);
			TweenAlphaWrap.Register(env);
			TweenShaderValueWrap.Register(env);
			TweenColorWrap.Register(env);
			TweenPathWrap.Register(env);
			TweenPositionWrap.Register(env);
			TweenTargetWrap.Register(env);
			TweenRotationWrap.Register(env);
			TweenScaleWrap.Register(env);
			TweenSliderWrap.Register(env);
			TweenImageFillAmountWrap.Register(env);
			TweenFovWrap.Register(env);
			TweenTimeScaleWrap.Register(env);
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "Game");
			UIClickListenerWrap.Register(env);
			UIDragListenerWrap.Register(env);
			UITouchListenerWrap.Register(env);
			InputListenerWrap.Register(env);
			UnitStateListenerWrap.Register(env);
			JoystickListenerWrap.Register(env);
			UIPointerDownListenerWrap.Register(env);
			UIPointerUpListenerWrap.Register(env);
			UIPointerExitListenerWrap.Register(env);
			UIButtonScaleWrap.Register(env);
			FyScrollRectWrap.Register(env);
			ArrayHelperWrap.Register(env);
			ByteArrayWrap.Register(env);
			UnitFollowerWrap.Register(env);
			ParticleFollowerWrap.Register(env);
			ResLoaderWrap.Register(env);
			UrlAssetRequestWrap.Register(env);
			UrlAssetWrap.Register(env);
			AssetWrap.Register(env);
			RequestBaseWrap.Register(env);
			AssetRequestWrap.Register(env);
			DownloadRequestWrap.Register(env);
			RangeLoaderWrap.Register(env);
			TileMapWrap.Register(env);
			ToolsWrap.Register(env);
			ElementsMapperWrap.Register(env);
			MapViewportCheckerWrap.Register(env);
			TransformFollowerWrap.Register(env);
			TimerWrap.Register(env);
			ProfilerWrap.Register(env);
			SpecialAnimationPlayerWrap.Register(env);
			InvokerWrap.Register(env);
			UGUIAltasWrap.Register(env);
			SystemSDKWrap.Register(env);
			FixedMessageBoxWrap.Register(env);
			BuildDefinesWrap.Register(env);
			AfterImageEffectsWrap.Register(env);
			CameraEffectWrap.Register(env);
			IosSdkWrap.Register(env);
			ItemAppearEffectWrap.Register(env);
			DonotDestroyManagerWrap.Register(env);
			ConfigWrap.Register(env);
			LogWrap.Register(env);
			CustomBehaviourWrap.Register(env);
			UIFixedListWrap.Register(env);
			UIListWrap.Register(env);
			UIListItemWrap.Register(env);
			UIGroupListWrap.Register(env);
			UIGroupListItemWrap.Register(env);
			UIPolygonWrap.Register(env);
			DynCallerWrap.Register(env);
			MemValueRegisterWrap.Register(env);
			PCStreamingSettingWrap.Register(env);
			EffectBinderWrap.Register(env);
			BarcodeWrap.Register(env);
			ThreeDToolsWrap.Register(env);
			SceneDataWrap.Register(env);
			FPSWrap.Register(env);
			ModelMaterialPresetWrap.Register(env);
			AnimationCurveListWrap.Register(env);
			DoubleDefineListWrap.Register(env);
			ColorDefineListWrap.Register(env);
			RadialBlurRendererWrap.Register(env);
			CameraRecWrap.Register(env);
			NiceInvokerWrap.Register(env);
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.HideFlags));
			RegHelper.RegisteEnum(env, typeof(System.TypeCode));
			RegHelper.RegisteEnum(env, typeof(System.Reflection.BindingFlags));
			RegHelper.RegisteEnum(env, typeof(System.Reflection.MemberTypes));
			RegHelper.RegisteEnum(env, typeof(System.Reflection.CallingConventions));
			RegHelper.RegisteEnum(env, typeof(System.Reflection.TypeAttributes));
			RegHelper.RegisteEnum(env, typeof(System.Reflection.GenericParameterAttributes));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.SendMessageOptions));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AnisotropicFiltering));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.TextureDimension));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.FilterMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.TextureWrapMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.ShadowCastingMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.MotionVectorGenerationMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.LightProbeUsage));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.ReflectionProbeUsage));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.SpriteMeshType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.SpritePackingMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.SpritePackingRotation));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.WrapMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AI.NavMeshPathStatus));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.MaterialGlobalIlluminationFlags));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.TextureFormat));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.RenderTextureFormat));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.RenderTextureReadWrite));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.VRTextureUsage));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.SkinQuality));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ParticleSystemVertexStream));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ParticleSystemRenderMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ParticleSystemRenderSpace));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ParticleSystemSortMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.PrimitiveType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Space));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AvatarIKGoal));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AvatarIKHint));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.HumanBodyBones));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AvatarTarget));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AnimatorUpdateMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AnimatorCullingMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AnimatorRecorderMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.CameraEvent));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.RenderingPath));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.OpaqueSortMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.TransparencySortMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.CameraClearFlags));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.CameraType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.StereoTargetEyeMask));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.DepthTextureMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ParticleSystemCustomData));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ParticleSystemStopBehavior));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AudioSourceCurveType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.FFTWindow));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AudioVelocityUpdateMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AudioRolloffMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AudioClipLoadType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AudioDataLoadState));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.RenderMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.AdditionalCanvasShaderChannels));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.LogType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.StackTraceLogType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UserAuthorization));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.RuntimePlatform));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ApplicationInstallMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ApplicationSandboxType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.SystemLanguage));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ThreadPriority));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.NetworkReachability));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ScreenOrientation));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.BatteryStatus));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.OperatingSystemFamily));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.GraphicsDeviceType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.CopyTextureSupport));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.NPOTSupport));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.DeviceType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.MeshTopology));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.CubemapFace));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.GraphicsTier));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.LightEvent));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.ShadowMapPass));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.LightType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.LightShadows));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Rendering.LightShadowResolution));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.LightRenderMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ShadowQuality));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ShadowProjection));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ShadowResolution));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.ColorSpace));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.BlendWeights));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.SceneManagement.LoadSceneMode));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.Texture2D");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Texture2D.EXRFlags));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.Camera");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Camera.StereoscopicEye));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.Camera.MonoOrStereoscopicEye));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.RectTransform");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.RectTransform.Edge));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.RectTransform.Axis));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.PointerEventData");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.EventSystems.PointerEventData.InputButton));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.UI");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.CanvasUpdate));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.TextAnchor));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.HorizontalWrapMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.VerticalWrapMode));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.FontStyle));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.TouchScreenKeyboardType));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.UI.Selectable");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.Selectable.Transition));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.UI.Image");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.Image.Type));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.Image.FillMethod));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.UI.Slider");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.Slider.Direction));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.UI.ScrollRect");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.ScrollRect.MovementType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.ScrollRect.ScrollbarVisibility));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.UI.Scrollbar");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.Scrollbar.Direction));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "UnityEngine.UI.InputField");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.InputField.ContentType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.InputField.LineType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.InputField.InputType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.InputField.CharacterValidation));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "Tween.UITweener");
			RegHelper.RegisteEnum(env, typeof(UITweener.Method));
			RegHelper.RegisteEnum(env, typeof(UITweener.Style));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "Tween");
			RegHelper.RegisteEnum(env, typeof(AnimationOrTween.Direction));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "Game.FyScrollRect");
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.FyScrollRect.MovementType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.UI.FyScrollRect.ScrollbarVisibility));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_mod_start(env, "Game");
			RegHelper.RegisteEnum(env, typeof(QuakeDirection));
			RegHelper.RegisteEnum(env, typeof(AssetPriority));
			RegHelper.RegisteEnum(env, typeof(UrlAssetType));
			RegHelper.RegisteEnum(env, typeof(UnityEngine.KeyCode));
			Native.jvm_reg_mod_end(env);
			Native.jvm_reg_end(env);
		}
	}
}
