import { Global as G } from 'System/global'
import { Macros } from 'System/protocol/Macros'
import { KeyWord } from 'System/constants/KeyWord'

/**
 * <宗门规则>枚举类。
 * Code generated by Bat&Perl.
 *
 * @author Administrator
 *
 */
export class GuildRule {
    /**<宗门仓库每页格子数>。*/
    static DEPOTE_PAGE_SIZE: number = 48; 
    /**<宗门仓库最大页数>。*/
    static DEPOTE_MAX_PAGE: number = 5; 
    /**<宗门仓库最低捐献阶级>。*/
    static DEPOTE_MIN_STAGE: number = 3; 
    /**<宗门仓库最高捐献阶级>。*/
    static DEPOTE_MAX_STAGE: number = 9; 
		
    /**<宗门分配每页>。*/
    static ALLOT_PAGE_SIZE: number = 6; 
    /**<宗门申请每页>。*/
    static APPLY_PAGE_SIZE: number = 5; 
    /**<宗门记录每页>。*/
    static RECORD_PAGE_SIZE: number = 6; 
    /**<宗门结算记录每页>。*/
    static RECORD_JIESUAN_PAGE_SIZE: number = 6; 
    /**<宗门记录每页>。*/
    static GUILD_FIGHT_PAGE_SIZE: number = 10; 
    /**<宗门列表每页>。*/
    static GUILD_LIST_INFO_PAGE_SIZE: number = 11; 
    /**<宗门捐献面板每页>。*/
    static GuildDonateDialog_PAGE_SIZE: number = 8; 
		
    /**<宗门仓库捐献面板每页>。*/
    static GuildDepotDonateDialog_PAGE_SIZE: number = 35; 
		
    /**<宗门分配最大可分配物品数量>。*/
    static ALLOT_MAX_COUNT: number = 6; 
		
    /**<招募需要钻石数>。*/
    static RECRUIT_COST_MONEY: number = 2; 
		
    /**捐献类型*/
    static TYPE_INTO: number = Macros.GUILD_STORE_LOG_INTO;
    /**兑换类型*/
    static TYPE_TAKE_OUT: number = Macros.GUILD_STORE_LOG_TAKEOUT;
    /**分配类型*/
    static TYPE_ALLOT: number = Macros.GUILD_STORE_LOG_ASSIGN;
    /**摧毁类型*/
    static TYPE_DISPOSE: number = Macros.GUILD_STORE_DELETE;

    /**申请类型*/
    static TYPE_APPLY: number = 4; 
    /**全部类型*/
    static TYPE_ALL: number = 5; 
		
    /**宗门位置等级*/
    static POS_LEVEL: number[] = [Macros.GUILD_GRADE_CHAIRMAN, Macros.GUILD_GRADE_VICE_CHAIRMAN, Macros.GUILD_GRADE_ELDER, Macros.GUILD_GRADE_MEMBER];

    /**宗门秘境BOSS ID*/
    static getSecretAreaBossId(): number {
        return G.DataMgr.constData.getValueById(KeyWord.ZMMJ_BOSS_ID_PARAM);
    }

    /**宗门秘境显示奖励读配置表的第几天*/
    static getSecretAreaRewardShowDay(): number {
        return G.DataMgr.constData.getValueById(KeyWord.ZMMJ_WEEK_DAY_PARAM);
    }
}
